# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_belt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_hired',
            field=models.DateField(),
        ),
    ]
