# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('python_belt', '0003_wishes_who'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishes',
            name='who',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='wishy', to='python_belt.users'),
        ),
    ]
