# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_belt', '0004_auto_20171001_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='mywish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(default=False, related_name='washy', to='python_belt.users')),
            ],
        ),
    ]
