# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('python_belt', '0006_mywish_liked'),
    ]

    operations = [
        migrations.CreateModel(
            name='favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('liked', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='python_belt.wishes')),
                ('likes', models.ManyToManyField(default=False, related_name='washy', to='python_belt.users')),
            ],
        ),
        migrations.RemoveField(
            model_name='mywish',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='mywish',
            name='likes',
        ),
        migrations.DeleteModel(
            name='mywish',
        ),
    ]
