# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_belt', '0008_auto_20171001_0505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishes',
            name='who',
        ),
        migrations.AddField(
            model_name='wishes',
            name='who',
            field=models.ManyToManyField(default=False, related_name='wishy', to='python_belt.users'),
        ),
    ]
