# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_belt', '0011_auto_20171001_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishes',
            old_name='whoose',
            new_name='who',
        ),
    ]
